var options = {
    solution: 			[[null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,  null,	'Z',	null,	null,	null,	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,  'F',	'U',	'S',	'E',	'L',	'A',	'G',	'E',	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,  null,	'L',	null,	null,	null,	'L',	null,	'N',	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,  null,	'U',	null,	null,	null,	'T',	null,	'G',	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,  null,	'T',	null,	null,	null,	'I',	'W',	'I',	'N',    'G',    null,   null,   null,   null,   null,   null,   'P',    null,   null],
                         [null,  null,	'I',	'T',	null,	null,	'M',	null,	'N',	null,   null,   null,   null,   null,   null,   null,   null,   'R',    null,   null],
                         [null,  null,	'M',	'A',	'C',	'H',	'E',	'D',	'E',	'S',    'C',    'E',    'N',    'T',    'A',    'K',    'E',    'O',    'F',     'F'],
                         [null,  null,	'E',	'I',	null,	null,	'T',	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   'P',    null,   null],
                         [null,	null,	null,	'L',	null,	null,	'E',	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   'E',    null,   null],
                         ['C',	'A',	'B',	'I',	'N',	'C',	'R',	'E',	'W',    null,   null,   null,   null,   null,   null,   null,   null,   'L',    null,   null],
                         [null,	null,	null,	null,	null,	'A',	null,	null,	null,   'T',    'H',    'R',    'U',    'S',    'T',    null,   null,   'L',    null,   null],
                         [null,	null,	null,	null,	null,	'R',	null,	null,	null,   null,   null,   'U',    null,   null,   'O',    null,   null,   'E',    null,   null],
                         [null,	null,	null,	null,	null,	'G',	null,	null,	null,   null,   null,   'N',    null,   null,   'R',    null,   null,   'R',    null,   null],
                         [null,	null,	null,	null,	null,	'O',	null,	null,	null,   null,   null,   'W',    null,   null,   'Q',    null,   null,   null,   null,   null],
                         [null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   null,   'A',    null,   null,   'U',    null,   null,   null,   null,   null],
                         [null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   null,   'Y',    null,   null,   'E',    null,   null,   null,   null,   null],
                         [null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,	null,	null,	null,	null,	null,	null,	null,	null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null]],


     index: 				[[null,  null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,      8,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,      1,   null,   null,   null,   null,      9,   null,     10,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,      6,   null,   null,   null,   null,   null,   null,   null,   null,   null,     15,   null,   null],
                         [null,   null,   null,     12,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,      2,   null,   null,   null,   null,      3,   null,   null,   null,   null,   null,      4,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [   5,   null,   null,   null,   null,     11,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,      7,   null,     14,   null,   null,     13,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null],
                         [null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null,   null]],

  questions_across: [	  "1. The main body of an aircraft",
                           "2. The ratio of aircraft speed to the speed of sound",
                           "3. A flight manueuver that causes a downward inclination",
                           "4. To leave the ground and start",
                           "5. The staff members responsible for the safety and comfort of the passengers",
                           "6. The piece of an aircraft that helps in aerodynamic lift",
                           "7. An aerodynamic force produced by the propeller or engine that pushes the craft forward"],

  questions_down: [		 "8. A term used for Universal Coordinated Time (UCT), also known as Greenwhich Mean Time",
                          "9. An instrument that measures an object's altitude above a fixed surface",
                          "10. The machine which powers the aircraft",
                          "11. Goods carried on an airplane",
                          "12. The aerodynamic surface located at the rear end of an aircraft",
                          "13. A force that aims to produce rotation",
                          "14. Area of ground for planes to land or takeoff",
                          "15. A rotating piece powered by the engine that produces thrust to propel the airplane into air"]

};


cwp_nmsp.activateCWP(document.getElementById("myPuzzle"),false,options);